{'src/collections_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/control_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/eratos_sieve_tests', [warnings_as_errors, {outdir, "ebin"}, {i, "../common/include"}]}.
{'src/grid_helper_tests', [warnings_as_errors, {outdir, "ebin"}, {i, "../common/include"}]}.
{'src/grid_path_searcher_tests', [warnings_as_errors, {outdir, "ebin"}, {i, "../common/include"}]}.
{'src/load_utils_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/number_dividers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/numbers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/pandigital_numbers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/permutations_tests', [warnings_as_errors, {outdir, "ebin"}]}.