namespace CommonLibTests

open CommonLib
open NUnit.Framework
open NUnit.Framework.Legacy
open System

[<TestFixture>]
type NumbersTests() =

    [<Test>]
    member public this.CalcFactorial() =
        // int
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcFactorial(-1) |> ignore) |> ignore
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(0))
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(1))
        ClassicAssert.AreEqual(2I, Numbers.CalcFactorial(2))
        ClassicAssert.AreEqual(6I, Numbers.CalcFactorial(3))
        ClassicAssert.AreEqual(24I, Numbers.CalcFactorial(4))
        ClassicAssert.AreEqual(120I, Numbers.CalcFactorial(5))
        ClassicAssert.AreEqual(720I, Numbers.CalcFactorial(6))
        ClassicAssert.AreEqual(5040I, Numbers.CalcFactorial(7))
        ClassicAssert.AreEqual(40320I, Numbers.CalcFactorial(8))
        ClassicAssert.AreEqual(362880I, Numbers.CalcFactorial(9))
        ClassicAssert.AreEqual(3628800I, Numbers.CalcFactorial(10))
        ClassicAssert.AreEqual(39916800I, Numbers.CalcFactorial(11))
        ClassicAssert.AreEqual(479001600I, Numbers.CalcFactorial(12))
        ClassicAssert.AreEqual(6227020800I, Numbers.CalcFactorial(13))
        ClassicAssert.AreEqual(87178291200I, Numbers.CalcFactorial(14))
        ClassicAssert.AreEqual(1307674368000I, Numbers.CalcFactorial(15))
        ClassicAssert.AreEqual(20922789888000I, Numbers.CalcFactorial(16))
        ClassicAssert.AreEqual(355687428096000I, Numbers.CalcFactorial(17))
        ClassicAssert.AreEqual(6402373705728000I, Numbers.CalcFactorial(18))
        ClassicAssert.AreEqual(121645100408832000I, Numbers.CalcFactorial(19))
        ClassicAssert.AreEqual(2432902008176640000I, Numbers.CalcFactorial(20))
        // int64
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcFactorial(-1L) |> ignore) |> ignore
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(0L))
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(1L))
        ClassicAssert.AreEqual(2I, Numbers.CalcFactorial(2L))
        ClassicAssert.AreEqual(6I, Numbers.CalcFactorial(3L))
        ClassicAssert.AreEqual(24I, Numbers.CalcFactorial(4L))
        ClassicAssert.AreEqual(120I, Numbers.CalcFactorial(5L))
        ClassicAssert.AreEqual(720I, Numbers.CalcFactorial(6L))
        ClassicAssert.AreEqual(5040I, Numbers.CalcFactorial(7L))
        ClassicAssert.AreEqual(40320I, Numbers.CalcFactorial(8L))
        ClassicAssert.AreEqual(362880I, Numbers.CalcFactorial(9L))
        ClassicAssert.AreEqual(3628800I, Numbers.CalcFactorial(10L))
        ClassicAssert.AreEqual(39916800I, Numbers.CalcFactorial(11L))
        ClassicAssert.AreEqual(479001600I, Numbers.CalcFactorial(12L))
        ClassicAssert.AreEqual(6227020800I, Numbers.CalcFactorial(13L))
        ClassicAssert.AreEqual(87178291200I, Numbers.CalcFactorial(14L))
        ClassicAssert.AreEqual(1307674368000I, Numbers.CalcFactorial(15L))
        ClassicAssert.AreEqual(20922789888000I, Numbers.CalcFactorial(16L))
        ClassicAssert.AreEqual(355687428096000I, Numbers.CalcFactorial(17L))
        ClassicAssert.AreEqual(6402373705728000I, Numbers.CalcFactorial(18L))
        ClassicAssert.AreEqual(121645100408832000I, Numbers.CalcFactorial(19L))
        ClassicAssert.AreEqual(2432902008176640000I, Numbers.CalcFactorial(20L))
        // bigint
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcFactorial(-1I) |> ignore) |> ignore
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(0I))
        ClassicAssert.AreEqual(1I, Numbers.CalcFactorial(1I))
        ClassicAssert.AreEqual(2I, Numbers.CalcFactorial(2I))
        ClassicAssert.AreEqual(6I, Numbers.CalcFactorial(3I))
        ClassicAssert.AreEqual(24I, Numbers.CalcFactorial(4I))
        ClassicAssert.AreEqual(120I, Numbers.CalcFactorial(5I))
        ClassicAssert.AreEqual(720I, Numbers.CalcFactorial(6I))
        ClassicAssert.AreEqual(5040I, Numbers.CalcFactorial(7I))
        ClassicAssert.AreEqual(40320I, Numbers.CalcFactorial(8I))
        ClassicAssert.AreEqual(362880I, Numbers.CalcFactorial(9I))
        ClassicAssert.AreEqual(3628800I, Numbers.CalcFactorial(10I))
        ClassicAssert.AreEqual(39916800I, Numbers.CalcFactorial(11I))
        ClassicAssert.AreEqual(479001600I, Numbers.CalcFactorial(12I))
        ClassicAssert.AreEqual(6227020800I, Numbers.CalcFactorial(13I))
        ClassicAssert.AreEqual(87178291200I, Numbers.CalcFactorial(14I))
        ClassicAssert.AreEqual(1307674368000I, Numbers.CalcFactorial(15I))
        ClassicAssert.AreEqual(20922789888000I, Numbers.CalcFactorial(16I))
        ClassicAssert.AreEqual(355687428096000I, Numbers.CalcFactorial(17I))
        ClassicAssert.AreEqual(6402373705728000I, Numbers.CalcFactorial(18I))
        ClassicAssert.AreEqual(121645100408832000I, Numbers.CalcFactorial(19I))
        ClassicAssert.AreEqual(2432902008176640000I, Numbers.CalcFactorial(20I))

    [<Test>]
    member public this.CalcBinomialCoeff() =
        // int
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1, -1) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1, 0) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1, 1) |> ignore) |> ignore
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5, -1))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(0, 0))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1, 0))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1, 1))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2, 0))
        ClassicAssert.AreEqual(2I, Numbers.CalcBinomialCoeff(2, 1))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2, 2))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3, 0))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3, 1))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3, 2))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3, 3))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4, 0))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4, 1))
        ClassicAssert.AreEqual(6I, Numbers.CalcBinomialCoeff(4, 2))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4, 3))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4, 4))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5, 0))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5, 1))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5, 2))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5, 3))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5, 4))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5, 5))
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5, 666))
        // int64
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1L, -1L) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1L, 0L) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1L, 1L) |> ignore) |> ignore
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5L, -1L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(0L, 0L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1L, 0L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1L, 1L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2L, 0L))
        ClassicAssert.AreEqual(2I, Numbers.CalcBinomialCoeff(2L, 1L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2L, 2L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3L, 0L))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3L, 1L))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3L, 2L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3L, 3L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4L, 0L))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4L, 1L))
        ClassicAssert.AreEqual(6I, Numbers.CalcBinomialCoeff(4L, 2L))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4L, 3L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4L, 4L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5L, 0L))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5L, 1L))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5L, 2L))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5L, 3L))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5L, 4L))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5L, 5L))
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5L, 666L))
        // bigint
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1I, -1I) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1I, 0I) |> ignore) |> ignore
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.CalcBinomialCoeff(-1I, 1I) |> ignore) |> ignore
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5I, -1I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(0I, 0I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1I, 0I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(1I, 1I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2I, 0I))
        ClassicAssert.AreEqual(2I, Numbers.CalcBinomialCoeff(2I, 1I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(2I, 2I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3I, 0I))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3I, 1I))
        ClassicAssert.AreEqual(3I, Numbers.CalcBinomialCoeff(3I, 2I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(3I, 3I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4I, 0I))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4I, 1I))
        ClassicAssert.AreEqual(6I, Numbers.CalcBinomialCoeff(4I, 2I))
        ClassicAssert.AreEqual(4I, Numbers.CalcBinomialCoeff(4I, 3I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(4I, 4I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5I, 0I))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5I, 1I))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5I, 2I))
        ClassicAssert.AreEqual(10I, Numbers.CalcBinomialCoeff(5I, 3I))
        ClassicAssert.AreEqual(5I, Numbers.CalcBinomialCoeff(5I, 4I))
        ClassicAssert.AreEqual(1I, Numbers.CalcBinomialCoeff(5I, 5I))
        ClassicAssert.AreEqual(0I, Numbers.CalcBinomialCoeff(5I, 666I))

    [<Test>]
    member public this.IsPerfectSquare() =
        // int
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> Numbers.IsPerfectSquare(-1) |> ignore) |> ignore
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(0))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(2))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(3))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(4))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(5))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(6))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(7))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(8))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(9))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1001 * 1002))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1002 * 1002))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1003 * 1002))
        // int64
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(0L))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(2L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(3L))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(4L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(5L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(6L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(7L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(8L))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(9L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1001L * 1002L))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1002L * 1002L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1003L * 1002L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212231L * 11212233L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212232L * 11212233L))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(11212233L * 11212233L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212234L * 11212233L))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212235L * 11212233L))
        // bigint
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(0I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(2I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(3I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(4I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(5I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(6I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(7I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(8I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(9I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1001I * 1002I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1002I * 1002I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1003I * 1002I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212231I * 11212233I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212232I * 11212233I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(11212233I * 11212233I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212234I * 11212233I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(11212235I * 11212233I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1121223123454I * 1121223123456I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1121223123455I * 1121223123456I))
        ClassicAssert.IsTrue(Numbers.IsPerfectSquare(1121223123456I * 1121223123456I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1121223123457I * 1121223123456I))
        ClassicAssert.IsFalse(Numbers.IsPerfectSquare(1121223123458I * 1121223123456I))
