namespace CommonLibTests

open CommonLib
open NUnit.Framework
open NUnit.Framework.Legacy
open System

[<TestFixture>]
type PandigitalNumbersTests() =

    [<Test>]
    member public this.IsPandigitalBadArgs() =
        // int
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> PandigitalNumbers.IsPandigital(-1) |> ignore) |> ignore
        // int64
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> PandigitalNumbers.IsPandigital(-1L) |> ignore) |> ignore
        // bigint
        Assert.Throws<ArgumentOutOfRangeException>(fun() -> PandigitalNumbers.IsPandigital(-1I) |> ignore) |> ignore

    [<Test>]
    member public this.IsPandigital2() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(0))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(13))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(21))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(31))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(0L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(13L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(21L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(31L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(0I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(13I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(21I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(31I))

    [<Test>]
    member public this.IsPandigital3() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(100))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(124))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(211))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(213))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(231))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(301))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(323))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(100L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(124L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(211L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(213L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(231L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(301L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(323L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(100I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(124I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(211I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(213I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(231I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(301I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(323I))

    [<Test>]
    member public this.IsPandigital4() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1000))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1233))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1235))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1324))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1399))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2314))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2333))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3421))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3422))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3425))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4444))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1000L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1233L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1235L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1324L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1399L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2314L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2333L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3421L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3422L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3425L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4444L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1000I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1233I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1235I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1324I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1399I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2314I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2333I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3421I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3422I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3425I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4444I))

    [<Test>]
    member public this.IsPandigital5() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10000))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(11111))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12346))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(13452))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(16666))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23451))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(23455))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(24531))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(24532))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(32415))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(32511))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(35421))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(35423))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(41235))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(41239))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(54321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54444))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10000L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(11111L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12346L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(13452L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(16666L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23451L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(23455L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(24531L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(24532L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(32415L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(32511L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(35421L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(35423L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(41235L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(41239L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(54321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54444L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(10000I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(11111I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12346I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(13452I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(16666I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23451I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(23455I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(24531I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(24532I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(32415I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(32511I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(35421I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(35423I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(41235I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(41239I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(54321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(54444I))

    [<Test>]
    member public this.IsPandigital6() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(111111))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123455))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123457))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(214356))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(222456))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321456))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(332211))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(461253))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(465559))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(543216))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(567890))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(654321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(654322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(765432))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(111111L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123455L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123457L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(214356L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(222456L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321456L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(332211L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(461253L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(465559L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(543216L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(567890L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(654321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(654322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(765432L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(111111I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123455I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123457I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(214356I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(222456I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(321456I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(332211I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(461253I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(465559I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(543216I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(567890I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(654321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(654322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(765432I))

    [<Test>]
    member public this.IsPandigital7() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1111111))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234566))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234567))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1333333))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2456731))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2456733))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3217654))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3333333))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4761235))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4812365))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(5671234))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(5761233))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(6125437))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(6345345))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(7654321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7654322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7888881))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1111111L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234566L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234567L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1333333L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2456731L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2456733L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3217654L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3333333L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4761235L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4812365L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(5671234L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(5761233L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(6125437L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(6345345L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(7654321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7654322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7888881L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1111111I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234566I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1234567I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1333333I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2456731I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2456733I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3217654I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3333333I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4761235I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4812365I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(5671234I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(5761233I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(6125437I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(6345345I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(7654321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7654322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7888881I))

    [<Test>]
    member public this.IsPandigital8() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12223344))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345677))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345678))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345679))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23456781))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22222234))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(38765412))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(39112233))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(45123876))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(45546776))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(51243768))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(51112222))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(61872435))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(61231236))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(72314586))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(78878800))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(87654321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(87654322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(88000000))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12223344L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345677L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345678L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345679L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23456781L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22222234L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(38765412L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(39112233L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(45123876L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(45546776L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(51243768L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(51112222L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(61872435L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(61231236L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(72314586L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(78878800L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(87654321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(87654322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(88000000L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12223344I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345677I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(12345678I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(12345679I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(23456781I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(22222234I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(38765412I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(39112233I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(45123876I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(45546776I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(51243768I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(51112222I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(61872435I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(61231236I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(72314586I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(78878800I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(87654321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(87654322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(88000000I))

    [<Test>]
    member public this.IsPandigital9() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122233445))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123456780))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456789))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(134567890))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(298765431))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299991234))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312645978))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(331122445))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(432198765))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(441212125))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(513246879))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(534678900))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(673451289))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(688668867))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(789123456))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(798765432))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(813579246))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(888888888))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(987654321))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(987654322))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(990001234))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122233445L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123456780L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456789L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(134567890L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(298765431L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299991234L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312645978L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(331122445L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(432198765L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(441212125L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(513246879L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(534678900L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(673451289L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(688668867L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(789123456L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(798765432L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(813579246L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(888888888L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(987654321L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(987654322L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(990001234L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(122233445I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(123456780I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(123456789I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(134567890I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(298765431I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(299991234I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(312645978I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(331122445I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(432198765I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(441212125I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(513246879I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(534678900I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(673451289I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(688668867I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(789123456I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(798765432I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(813579246I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(888888888I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(987654321I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(987654322I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(990001234I))

    [<Test>]
    member public this.IsPandigital10() =
        // int
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1010101012))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1023456788))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1023456789))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234567899))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2013456789))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2113456789))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(Int32.MaxValue))
        // int64
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1010101012L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1023456788L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1023456789L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234567899L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2345678910L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2456456456L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3210987654L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3334567890L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4589123067L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4677655899L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(5012346789L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(5556667770L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(6135792480L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(6666666666L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(7986543210L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7998866554L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(8123456097L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(8343412129L))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(9876543210L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(9876543211L))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(9988776654L))
        // bigint
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1010101012I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1023456788I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(1023456789I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(1234567899I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(2345678910I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(2456456456I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(3210987654I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(3334567890I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(4589123067I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(4677655899I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(5012346789I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(5556667770I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(6135792480I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(6666666666I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(7986543210I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(7998866554I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(8123456097I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(8343412129I))
        ClassicAssert.IsTrue(PandigitalNumbers.IsPandigital(9876543210I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(9876543211I))
        ClassicAssert.IsFalse(PandigitalNumbers.IsPandigital(9988776654I))