{'src/collections_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/compare_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/control_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/eratos_sieve_tests', [warnings_as_errors, {outdir, "ebin"}, {i, "../common/include"}]}.
{'src/grid_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/grid_path_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/load_utils_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/mutable_uint8_array_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/number_dividers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/numbers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/pandigital_numbers_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/partition_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/pell_equation_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/permutations_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/rational_tests', [warnings_as_errors, {outdir, "ebin"}]}.
{'src/string_utils_tests', [warnings_as_errors, {outdir, "ebin"}]}.